name: pint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run pint
        uses: wbollock/pint-action@v1.0.1
        with:
          token: ${{ github.token }}
          workdir: 'rules'
          pr_target_repo: ${{ github.event.pull_request.base.repo.full_name }}
          pr_source_repo: ${{ github.event.pull_request.head.repo.full_name }}
